### ISSUE TITLE
Todo/Issues

### ISSUE THREAD

**Issue by Unitech** [gridcontrol/gridcontrol#19]
# Todo
- [ ] private multissh
- [ ] check PR on nvm for aarch64 support (odroid c2) https://github.com/creationix/nvm/pull/1104 and update install.sh nvm script
- [ ] Homogeneize grid provision and grid keycopy  (both need a hostfile or user@ip combination)
- [ ] grid hostfile: should be able to seperate user and ip with a : or @
- [ ] allow to pass a password when doing `grid provision`
- [ ] load balancer: implement broadcast strategy
- [ ] keep stats of tasks invocation
- [ ] implement test with new PM2
- [ ] blessed contrib dashboard (for RIG also)
- [ ] POC with python/java app
# Issues
